[package]
name = "unions"
version = "0.1.0"
edition = "2024"

[lib]
name = "unions"
path = "src/lib.rs"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[profile.dev]
opt-level = 3
lto = true
panic = 'abort'
incremental = false